[package]
name = "phaestus_platformer_tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9"
bevy_editor_pls = {git = "https://github.com/jakobhellermann/bevy_editor_pls"}
rand = "0.8"
leafwing-input-manager = "0.8.0"
bevy_rapier2d = "*"
bevy-inspector-egui-rapier = { version = "*", features = ["rapier2d"]}

[profile.dev.package."*"]
opt-level = 3